### ISSUE TITLE
Kernel driver quick review

### ISSUE THREAD

**Issue by gregkh** [desertbit/openrazer-drivers#2]
- [x] Use DEV_ATTR_RW(), DEV_ATTR_RO() and DEV_ATTR_WO() and not "raw" DEV_ATTR().
- [ ] Do not use // for comments
- [ ] Use an attribute group, not bunches of device_add_file() calls.
- [x] Drop all of the EXPORT_SYMBOL_GPL() as you don't use or need it at all
- [ ] run 'sparse' on the code and fix up the issues found
- [x] merge it all to one file, no need for multiple files for a single simple driver
- [ ] document the sysfs files in a Documentatation/ABI/ style file so that people can review them easily
- [ ] don't use pr__() calls, always use dev__() calls instead, you are a driver, you have a device, use it.
- [ ] Don't attach to the usb device, but rather the interface, as that is what you "own", not that device.
- [ ] properly check for endian issues (again, sparse will catch that)
- [ ] don't use 'uint', use unsigned int if you really need it, or better yet u32, u64, or u8 as needed.
- [ ] a lot of the 'return this value for this type of device' functions could just be a simple lookup in a simple table, making it much easier to add new device support in the future without having to go around and try to remember all of the places it needs to be added to.  Also makes the code simpler and easier to understand.

That's a good enough start :)

**Comment by r0l1** [comment]
Great thanks a lot! I'll work on it and inform you as soon as I am ready with it. I'll also cancel the kernel patch previously send to the mailing lists.

**Comment by r0l1** [comment]
@gregkh I received an e-mail from the linux mailing list.

Quote from Benjamin Tissoires:

> I saw your other email, but I still wants to make some high-level review
> so that you don't spend too much time in code you will need to remove.
> 
> So here they come:
> Generally, it is better to keep the kernel interface to a minimum. It's
> OK to enable macro keys from the kernel, but setting the color of the
> keyboard is something which should be done IMO in userspace only through
> hidraw.
> 
> The reasons are:
> - maintaining a kernel API is a pain
> - you basically can't change it while it's there given that you might
>   have users using it
> - roccat used to have a kernel API, and the latest userspace version
>   of the tool went away from this given that it was too much of a pain
>   and using hidraw allows a lot more flexibility
> - we have standard API for LED, and you are not using them
> - add some more which would convince you 
> 
> Please have a look at what hidraw offers and think twice before adding a
> sysfs API for a functionality (I'll give you my ideas below). You can
> see what we are doing for Logitech and some others in libratbag
> (github.com/libratbag/libratbag) or what roccat (the open project, not
> the company) did.

I must admit, that he is absolutely right and that's the way to go. I'll work on a hidraw driver in userspace and stop the development of the kernel driver :smiley:

**Comment by aidansteele** [comment]
@m4ng0squ4sh What are your thoughts on using [`hidapi`](https://github.com/signal11/hidapi) instead of `hidraw` directly? 

One advantage of this would be easier cross-platform compatibility. I currently use my Chroma device on a Mac, but absolutely loathe the official Razer GUI. I'll be starting work using `hidapi` for my own device, but it might be useful to combine efforts?

**Comment by r0l1** [comment]
@aidansteele Sounds great! My colleges are all Mac users (They own some Razer devices) and I like the idea of a cross-platform common driver. I'll spend time on the OpenRazer Project in October/November, but I am always open to discuss and plan the design. Let's start with some initial tests using hidapi in a new repository and define the overall application design.

Feel free to join the [Gitter Chat](https://gitter.im/openrazer/General?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for further discussion.

**Comment by aidansteele** [comment]
@m4ng0squ4sh thanks for the very quick response! I've joined the Gitter chat (I _think_, first time so not sure!) and appreciate the quick access to the github org - I'll start spelunking on my end on a branch of the hidapi repo and keep you informed. I'll probably have a million questions along the way too.

**Comment by r0l1** [comment]
@aidansteele Welcome aboard!

> I'll start spelunking on my end on a branch of the hidapi repo and keep you informed.

Great! Excited to see this project evolve.

> I'll probably have a million questions along the way too.

I'll try to help solving them :)

**Comment by gregkh** [comment]
No longer an issue, this shouldn't be a kernel driver :)
